### ISSUE TITLE
Feat: create `dart` version of `cid` package

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dart_cid#1]
At present there is no package on `pub.dev` matching the keyword "cid": https://pub.dev/packages?q=cid

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/194400/200697660-5f2fdf3d-cecc-4876-bb0d-f53827989fae.png">

https://pub.dev/packages/cid
<img width="941" alt="image" src="https://user-images.githubusercontent.com/194400/200697589-6ad68533-1f05-47a9-bd88-ec874f5e003a.png">

# Todo

+ [x] Port the `Elixir` code from https://github.com/dwyl/cid to this repo in `dart-lang` ♻️ 
+ [x] Create a Pull Request to get early feedback on code. 🆕 
+ [x] Publish the package to `pub.dev` this will be our _first_ `dart` package! 📦 
  + [x] Document the process for publishing a package:   https://github.com/dwyl/learn-dart/issues/22
> **Note**: for biz continuity purposes, the package will be published under the **`dwyl`** namespace/ownership.
  

There appear to be a few options available for **`Base 58`** in `dart`:  https://pub.dev/packages?q=base58
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/194400/200697434-873ff787-d7c2-46b7-9c03-bafa475b5aac.png">

So at least we don't need to implement that part before being able to build **`cid`** in `dart`. 👌

**Comment by nelsonic** [comment]
@LuchoTurtle as discussed on Standup this morning,
If you want to fork the https://github.com/C0MM4ND/dart_fast_base58 for security reasons
and include it as a `git` dependency in our `cid` implementation, go for it:

```yml
dependencies:
  flutter:
    sdk: flutter

  dart_fast_base58:
    git:
      url: https://github.com/dwyl/dart_fast_base58.git
      ref: main # branch name
```

**Comment by LuchoTurtle** [comment]
Having read:
https://sovereign-individual.xyz/posts/future-proof-crypto-hashes/
https://sovereign-individual.xyz/posts/ipfs-content-identifiers/
https://docs.ipfs.tech/concepts/content-addressing/#cid-conversion
https://multiformats.io/multihash/

and perusing dwyl's CID implementation at https://github.com/dwyl/cid/blob/master/lib/cid.ex,

I tried to search for implementations of `Multihash` I could use in Dart and found there to be [none](https://github.com/multiformats/multihash#implementations). The closest I found was [multibase](https://github.com/multiformats/multibase#implementations), which really isn't [the same thing](https://www.google.com/search?q=multihash+vs+multibase&oq=multihash+vs+multibase&aqs=chrome..69i57j69i60l3j69i65j69i60j69i65l2.3228j0j1&sourceid=chrome&ie=UTF-8) and it's not how IPFS does things.

So should I try to implement my own version of Multihash in Dart? Never done this nor done anything crypto-related 😅 . 

What do you think? 

@nelsonic

**Comment by nelsonic** [comment]
@LuchoTurtle Good research and follow-up question. 👍 
We can do the `Multihash` _later_. It's not a prerequisite for `cid`. 💭 
Once we have a _basic_ `cid` implementation in `Dart`, :shipit: 
enough to do what we need in our `Flutter` App, 📱 
very happy to do any deep-dives into more advanced features. ⏳ 

Please create an issue in the backlog for `Multihash` _now_ 🆕 
so we know what is _next_ and can link to it from the `README.md -> Roadmap` Section. 🔗 

Stoked you're getting a chance to dive into Crypto. 🔐 
It's a real differentiator on your CV to have a _deep_ technical understanding of the topic. 🤓 👌

**Comment by nelsonic** [comment]
If along your journey to understanding all this you learn new things, 🔍 
_please_ add a section to: https://github.com/dwyl/learn-cryptography 📝 🙏

**Comment by LuchoTurtle** [comment]
> We can do the Multihash later. It's not a prerequisite for cid. 💭

You are right it is not a prerequisite for CID. For CID v0 [it is not used](https://docs.ipfs.tech/concepts/content-addressing/#cid-conversion) but I feel like going for v1 would be better not only for us but for anyone who wants a `cid` in Dart. 
After doing research, I noticed that there wasn't a Dart implementation of Multihash so I went along and have an mvp working (encoding and decoding) -> https://github.com/dwyl/dart_cid/pull/2.

I still want to iron out a few features and then get it featured on the canonical repo of `multiformats` https://github.com/multiformats/multihash#implementations. There's more info on the PR https://github.com/dwyl/dart_cid/pull/2.

This will change the scope of the repo to Multihash. I will use this one and work on the CID making use of Multihash on a different one. Is that reasonable? 😄

**Comment by nelsonic** [comment]
@LuchoTurtle great that you _proactively_ implemented something. 
Figuring out how all of this works under the hood is a non-trivial task.
And you are growing leaps and bounds as an engineer by exploring it. 🎉 

Remember that:

# "_Writing `code`? That's the `easy` part. <br />Getting your application in the hands of users, <br />and creating applications that people actually want to use - now that's the hard stuff._" ~ [Jeff Atwood](https://blog.codinghorror.com/the-best-code-is-no-code-at-all/)


Now for the "not nice" part:

When I asked you to create an **issue** for **`Multihash`** it **wasn't a _suggestion_**. 
Issues are how we keep track of the work that needs to be done. Without them it's chaos.
I don't like Chaos and I don't know _any_ leader/entrepreneur who does. 
If they _say_ they do; they're either joking or _lying_. Chaos is the enemy of progress.

I say/write "***Please***" to be polite. But **_please_ don't confuse** **_direct_ instructions** for **_optional_ requests** again.
It's not _difficult_ to open an **issue** [5 mins] before spending a _day_ [8 hours] on a tangental task. 💭 

## Create an issue ***`before`*** you start the work

Here's the issue: https://github.com/dwyl/dart_multihash/issues/1 it took me **`T5m`** to create it.
My time is worth **`20x`** so **`5 minutes`** of my time is **`100 minutes`**  of yours ... [You're welcome](https://youtu.be/79DijItQXMM).

As far as "bosses" go, I `try` my best not to be an [**`A55H0L3`**](https://github.com/dwyl/learn-react/issues/23#issuecomment-1308947186)
but I've worked a few places where doing the [**_exact_ opposite**](https://github.com/dwyl/dart_cid/issues/1#issuecomment-1326475907)
of what the "boss" asks gets people [fired on-the-spot](https://levelup.gitconnected.com/why-elon-musk-fired-most-of-his-long-term-employees-who-had-worked-for-him-for-over-5-years-c94ac3120eba). 🔥 

## Remote Work === Communication. 

If you _want_ to work in micro-team in an office on closed source software
where written communication isn't required, that's fine. 
But if you want to work remotely, then **communicating** early and often is a [***`MUST`***](https://www.ietf.org/rfc/rfc2119.txt), **_not_ optional**.

I've worked on 200+ people remote teams and the engineers who ignore communication
get labelled as "_Difficult to Work With_" and get "let go" _very_ fast. 🙅 

I'm not saying this to be "mean" or "difficult", in fact the exact opposite is true!
As you know my goal is to help you grow and flourish as a person and engineer. 🚀 

I [`expect`](https://en.wikipedia.org/wiki/Pygmalion_effect) you to go on to do great things and work in _super_ interesting places.
But the number of those places in PT/Porto is _vanishingly_ small. 
Which means you either need to move away from all your family, friends & creature comforts
to a big international city where you know nobody, have zero friends or family and will be _miserable_.
***OR*** you have the "best of all worlds" and work remotely. 


## Your Time < My Time

Your "bosses" time will _always_ be more valuable than yours.
In some cases it's "only" `5x` but if you work somewhere "big" like Google, it's `100x`.
_Never_ waste your bosses time. _Ever_. 

When you [eventually] _become_ the "boss", e.g. when you start your own company.
You will want the people working for you to respect your time.
I sincerely hope you reach that point. 
Because the alternative is [mediocrity](https://youtu.be/rH94x03Wl-M) and _nobody_ wants that. 😢

**Comment by LuchoTurtle** [comment]
In the process of adding property-tests, akin to what's happening here -> https://github.com/dwyl/cid/blob/194d5e10d8713a6bce186d74021153ca43d5782a/test/cid_test.exs#L114

It's taking a wee of time to get it working the same, processes work a bit differently in Dart. But I should get it working today.
I kept README fairly simple because I didn't want to duplicate information from https://github.com/dwyl/cid

**Comment by nelsonic** [comment]
Good plan. thank you for being thorough. 👌

**Comment by LuchoTurtle** [comment]
Finished IPFS tests based on what was done with `dwyl/cid` -> https://github.com/dwyl/dart_cid/pull/3#issuecomment-1329059371

Regarding documenting the process of publishing a package https://github.com/dwyl/learn-dart/issues/22, I'm waiting for https://github.com/dwyl/dart_multihash/pull/2 to be reviewed so I can publish it, properly use it on this repo instead of mocking.

**Comment by nelsonic** [comment]
@LuchoTurtle https://github.com/dwyl/dart_multihash/pull/2 merged. :shipit: 
Please proceed. 🙏  (Thanks again!)

**Comment by LuchoTurtle** [comment]
Just pushed the necessary changes with https://github.com/dwyl/dart_cid/pull/3
Marked your comment as outdated by mistake, wanted to hide it to make scrolling easier but ended up making a mistake. Sorry about that.

**Comment by nelsonic** [comment]
PR #3 merged. Please publish. 📦 🚀 🙏

**Comment by LuchoTurtle** [comment]
Published 
https://pub.dev/packages/dart_cid
